import streamlit as st
import pandas as pd
import joblib
import os
from sklearn.metrics import confusion_matrix, classification_report

st.title("Breast Cancer Diagnosis Prediction")
st.write("This app uses 6 different ML models to classify breast cancer cases.")

# Requirement a: Dataset upload option [cite: 91]
uploaded_file = st.file_uploader("Upload Test Data (CSV)", type="csv")

# Requirement b: Model selection dropdown [cite: 92]
model_options = ["logistic_regression", "decision_tree", "knn", "naive_bayes", "random_forest", "xgboost"]
selected_model = st.selectbox("Select a Model", model_options)

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.write("Data Preview:", df.head())
    
    # Path to the model generated by your train_models.py
    model_path = f"model/{selected_model}.joblib"
    
    if os.path.exists(model_path):
        model = joblib.load(model_path)
        st.success(f"Model '{selected_model}' loaded successfully!")
        
        # Requirement c & d: Display metrics and confusion matrix [cite: 93, 94]
        st.subheader("Model Evaluation Results")
        st.info("Metrics and Confusion Matrix will be displayed here after prediction.")
    else:
        st.error(f"Model file {model_path} not found. Did you run train_models.py?")